### ISSUE TITLE
USDt payment method not created for EUR invoices alongside Bitcoin Lightning

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver-tether/BTCPayServer.Plugins.USDt#4]
There’s a bug when the server handles multiple currencies. When creating invoices in EUR, the USDT payment method (on Tron) is not generated, only the Bitcoin Lightning option. The expected behavior is that the EUR to USDT rate is fetched, and the USDT payment method is created. Everything works well when USD is the currency.

Here is a video that illustrates the problem.

https://github.com/user-attachments/assets/32d373a5-6127-469e-b98c-300179694bf5

**Comment by Nisaba** [comment]
Hello,
Still not working for me...
It works only for USD invoices, not EUR or anything else...
Also, I notices this file is empty in the repo:
https://github.com/btcpayserver-tether/BTCPayServer.Plugins.USDt/blob/master/BTCPayServer.Plugins.USDt/Views/Shared/TronUSDtLike/EmptyCheckoutPaymentMethodExtension.cshtml

Thanks

**Comment by rockstardev** [comment]
@Nisaba, seems something is wrong with your deployment. Make sure you have the latest version of your plugin. I've just tested and it works: 

![Image](https://github.com/user-attachments/assets/850b3871-b5af-41ac-810f-732eb82e6549)

**Comment by Nisaba** [comment]
Well, I've installed the plugin from BTCPay a few minutes before I post this comment, so it should be the last version ?
Or the version wich is downloaded is not the last ?

**Comment by rockstardev** [comment]
@Nisaba take a moment to record how problems looks on your end and post it here in the replies. Especially if you can also display logs. But it should work from what I see here in code: https://github.com/btcpayserver-tether/BTCPayServer.Plugins.USDt/blob/31c3b6f086bdc3d60fe09d181e754abb81d0b3a6/BTCPayServer.Plugins.USDt/USDtPlugin.cs#L107

The only problem that could potentially occur is if the exchange you selected does not support USDT_BTC & BTC_EUR rates.

**Comment by Nisaba** [comment]
Well, I've uninstalled and reinstalled the plugin and it works now
